### ISSUE TITLE
Update for 2021.2

### ISSUE THREAD

**Issue by larsivi** [vnea/intellij-plugin-quickly-change-editor-font-size-preference#1]
Hi! Could you please update the package for 2021.2?

**Comment by vnea** [comment]
Hello.

I was very busy sorry.

I have just submitted a new version and JetBrains is reviewing this update now.

**Comment by larsivi** [comment]
Awesome!

**Comment by vnea** [comment]
The new version (1.1.3) has been approved so you can update the plugin.
